senbox-org/snap-desktop

snap-rcp/src/main/java/org/esa/snap/rcp/colormanip/ColorManipulationForm.java

ProgressMonitorSwingWorker causes the blinking of windows at startup

---

snap-dem-ui/src/main/java/org/esa/snap/dem/rcp/AddElevationAction.java
snap-gpf-ui/src/main/java/org/esa/snap/rcp/mosaic/MosaicDialog.java
snap-gpf-ui/src/main/java/org/esa/snap/rcp/reproject/ReprojectionDialog.java

Luis, please check the changes we made. If you're not happy with some change we can still discuss it, otherwise simply accept the pull request.
cheers

Dem refactoring

---

ReleaseNotes.md
snap-rcp/src/main/java/org/esa/snap/rcp/about/SnapAboutBox.java
snap-rcp/src/main/java/org/esa/snap/rcp/util/BrowserUtils.java

add release notes to about boxes

Releasenotes

---

snap-rcp/src/main/java/org/esa/snap/rcp/actions/vector/VectorDataNodeImporter.java

allow multiple shape files be imported at once

---

snap-rcp/src/main/java/org/esa/snap/rcp/nodes/PNGGroup.java
snap-rcp/src/main/java/org/esa/snap/rcp/nodes/PNGroupingGroup.java
snap-rcp/src/main/java/org/esa/snap/rcp/nodes/PNode.java

Implemented support to allow the autogrouping in masks.

Support grouping for masks

---

snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/gpf/ui/ReprojectionUI.java
snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/gpf/ui/ResamplingUI.java
snap-graph-builder/src/main/resources/org/esa/snap/graphbuilder/layer.xml

Resampling: To avoid problems when changing the source product,
we should always use target width and height, but the output are not the same...
Reprojection: The functionality "Use CRS of" has been removed, it should be added in the future

Added specific BaseOperatorUI for Resampling and ReprojectionUI

---

snap-product-library/src/main/java/org/esa/snap/productlibrary/rcp/toolviews/ProductLibraryToolView.java
snap-rcp/src/main/java/org/esa/snap/rcp/actions/file/WriteProductOperation.java
snap-rcp/src/main/java/org/esa/snap/rcp/session/SaveSessionAction.java

Add new interface to session to saveAs another session file.
ignore the lazy load of icons. I forgot that commit was in here.

Session access

---

snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/gpf/ui/ResamplingUI.java

The resampling parameters were not loaded properly when loading a graph

fix SNAP-775

---

snap-gpf-ui/src/main/java/org/esa/snap/core/gpf/ui/TargetProductSelector.java
snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/gpf/ui/TargetUI.java

Always write product in WriteOp in Graph builder

Write op ui

---

snap-dem-ui/src/main/java/org/esa/snap/dem/gpf/ui/AddElevationOpUI.java

Reverts senbox-org/snap-desktop#40

Revert "Switch to allow for Geoid heights at NaN DEM-pixels"

---

snap-rcp/src/main/java/org/esa/snap/rcp/statistics/ExportStatisticsAsCsvAction.java
snap-rcp/src/main/java/org/esa/snap/rcp/statistics/PutStatisticsIntoVectorDataAction.java

Accept pull request in snap-engine first!

adapted to changes in statisticwriters

---

snap-ui/src/main/java/org/esa/snap/ui/product/ProductSubsetDialog.java

Changed the scroll bar unit increment in the subset dialog

change scrollbar increment

---

snap-rcp/src/main/java/org/esa/snap/rcp/mask/MaskFormActions.java

Copying the mask band was made with wrong expression before.

SNAP-842 (mask copying bug)

---

snap-pixel-extraction-ui/src/main/java/org/esa/snap/pixex/visat/PixelExtractionDialog.java
snap-pixel-extraction-ui/src/main/java/org/esa/snap/pixex/visat/PixelExtractionIOForm.java

Added correct reading of output directory from parameter file.

---

snap-ui/src/main/java/org/esa/snap/ui/ButtonOverlayControl.java
snap-ui/src/main/java/org/esa/snap/ui/WorldMapPane.java

Added zoom buttons to the world map and tooltips.

---

snap-ui/src/main/java/org/esa/snap/ui/product/ProductSubsetDialog.java

In following, I plan an other pull request on snap-engine to complete this issue.

manage negative dimension of the ui selected ROI

---

snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/gpf/ui/BaseOperatorUI.java
snap-raster-ui/src/main/java/org/esa/snap/raster/gpf/ui/CreateLandMaskOpUI.java
snap-raster-ui/src/main/java/org/esa/snap/raster/rasterModule.java
snap-raster-ui/src/main/resources/org/esa/snap/raster/docs/operators/CreateLandMask.html
snap-raster-ui/src/main/resources/org/esa/snap/raster/graphs/Raster/Land Sea Mask For Multi-size Source.xml

The source product is resampled with a reference band size. This operation occur before to apply the land mask operator .
The reference band will be selected by user.
The interpolation stay simple with nearest model.

SNAP-1057 add resampling operation parameters in case of multi-size products

---

snap-classification-ui/src/main/java/org/esa/snap/classification/ClassificationModule.java
snap-raster-ui/src/main/java/org/esa/snap/raster/RasterModule.java

Fix naming convention of the module class.

WIP: fix class naming convention part1

---

snap-rcp/src/main/java/org/esa/snap/rcp/status/PixelPosStatusLineElementProvider.java

Show features that are not currently available, like the scale or the pixel spacing.

SNAP-1028 improve status bar

---

snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/gpf/ui/SourceUI.java

JIRA: [SIITBX-410:](https://senbox.atlassian.net/browse/SIITBX-410)

SIITBX-410: Show Read nodes when XML graph loaded in Graph Builder UI fix.

---

snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/gpf/ui/SubsetUI.java

The update concern the pixel region parameter and reference band.

[SNAP-1501] update Subset parameters in Graph Builder

---

.gitlab-ci.yml
pom.xml

Main steps are :
- Build
- Test (UT)
- SCA
- Security check

[SCM-141]: Add main pipeline steps

---

snap-rcp/src/main/java/org/esa/snap/rcp/actions/vector/ImportTrackAction.java
snap-rcp/src/main/java/org/esa/snap/rcp/actions/vector/ImportVectorDataNodeFromCsvAction.java
snap-rcp/src/main/java/org/esa/snap/rcp/actions/vector/ImportVectorDataNodeFromMermaidAction.java
snap-rcp/src/main/java/org/esa/snap/rcp/actions/vector/ImportVectorDataNodeFromShapefileAction.java

Fixes issue where for some platforms some of the vector import tools are disabled in the Menu.

SEADAS: vector import menu disabled fix (master)

---

snap-product-library-ui-v2/src/main/java/org/esa/snap/product/library/ui/v2/repository/input/DateParameterComponent.java
snap-product-library-ui-v2/src/main/java/org/esa/snap/product/library/ui/v2/repository/local/AllLocalProductsRepositoryPanel.java
snap-product-library-ui-v2/src/main/java/org/esa/snap/product/library/ui/v2/repository/remote/RemoteProductsRepositoryPanel.java

Fix for [SNAP-3534](https://senbox.atlassian.net/browse/SNAP-3534).
[SNAP-3534]: https://senbox.atlassian.net/browse/SNAP-3534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3534_product-library

---

snap-rcp/src/main/java/org/esa/snap/rcp/util/TestProducts.java

little change to make test data reliable

make random test data reproducible

---

snap-product-library-ui-v2/src/main/java/org/esa/snap/product/library/ui/v2/preferences/RepositoriesCredentialsControllerUI.java

Fix for [SNAP-3602](https://senbox.atlassian.net/browse/SNAP-3602).
[SNAP-3602]: https://senbox.atlassian.net/browse/SNAP-3602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3602_snap-desktop

---

snap-gdal-writer-ui/src/main/java/org/esa/snap/gdal/writer/ui/WriterPlugInExportProductAction.java

Fix for [SNAP-3635](https://senbox.atlassian.net/browse/SNAP-3635)
[SNAP-3635]: https://senbox.atlassian.net/browse/SNAP-3635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3565 Export to GDAL fails with NoSuchMethodException

---

snap-land-cover-ui/src/main/java/org/esa/snap/landcover/gpf/ui/AddLandCoverOpUI.java
snap-land-cover-ui/src/main/java/org/esa/snap/landcover/rcp/AddLandCoverAction.java

SRM-186 worldcover
SNAP-3718  land cover ui to use tree

Srm 186 worldcover

---

snap-rcp/src/main/java/org/esa/snap/rcp/angularview/AngularTopComponent.java
snap-rcp/src/main/java/org/esa/snap/rcp/nodes/PNGGroup.java
snap-rcp/src/main/java/org/esa/snap/rcp/nodes/PNGroupingGroup.java
snap-rcp/src/main/java/org/esa/snap/rcp/nodes/PNode.java
snap-rcp/src/main/java/org/esa/snap/rcp/spectrum/SpectrumTopComponent.java
snap-remote-execution-ui/pom.xml
snap-ui/src/main/java/org/esa/snap/ui/product/BandChooser.java
snap-ui/src/main/java/org/esa/snap/ui/product/GroupedBandChoosingStrategy.java

Snap 3702 ext apply tb

---

snap-worldwind/pom.xml

Fix for [SNAP-3868](https://senbox.atlassian.net/browse/SNAP-3868).
[SNAP-3868]: https://senbox.atlassian.net/browse/SNAP-3868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3868_snap-worldwind

---

snap-ui/src/main/java/org/esa/snap/ui/product/ProductSubsetDialog.java

Fix for [SNAP-3779](https://senbox.atlassian.net/browse/SNAP-3779).
[SNAP-3779]: https://senbox.atlassian.net/browse/SNAP-3779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3779_subset-ui_bug

---

snap-rcp/src/main/java/org/esa/snap/rcp/actions/window/OpenHSVImageViewAction.java
snap-rcp/src/test/java/org/esa/snap/rcp/actions/window/OpenHSVImageViewActionTest.java

Fixed R/G/B expressions in HSV to RGB conversion

---

snap-product-library-ui-v2/src/main/java/org/esa/snap/product/library/ui/v2/ProductLibraryToolViewV2.java
snap-product-library-ui-v2/src/main/java/org/esa/snap/product/library/ui/v2/thread/ProgressBarHelperImpl.java
snap-rcp/src/main/java/org/esa/snap/rcp/SnapApp.java

Fix for [SNAP-3947](https://senbox.atlassian.net/browse/SNAP-3947).
[SNAP-3947]: https://senbox.atlassian.net/browse/SNAP-3947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3947_product-library

---

snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/gpf/ui/BaseOperatorUI.java
snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/gpf/ui/OperatorUI.java
snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/gpf/ui/ProductSetReaderOpUI.java
snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/gpf/ui/SourceUI.java
snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/gpf/ui/StatusLabel.java
snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/rcp/dialogs/GraphBuilderDialog.java
snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/rcp/dialogs/ProductSetPanel.java
snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/rcp/dialogs/support/GraphExecuter.java
snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/rcp/dialogs/support/GraphNode.java
snap-graph-builder/src/main/java/org/esa/snap/graphbuilder/rcp/dialogs/support/GraphPanel.java
snap-graph-builder/src/test/java/org/esa/snap/graphbuilder/gpf/ui/StatusLabelTest.java

Snap 4019 tb

---

snap-product-library-ui-v2/src/main/java/org/esa/snap/product/library/ui/v2/ProductLibraryToolViewV2.java
snap-product-library-ui-v2/src/main/java/org/esa/snap/product/library/ui/v2/thread/ProgressBarHelperImpl.java
snap-rcp/src/main/java/org/esa/snap/rcp/SnapApp.java

Fix for [SNAP-3947](https://senbox.atlassian.net/browse/SNAP-3947) and links to [SNAP-3997](https://senbox.atlassian.net/browse/SNAP-3997).
[SNAP-3947]: https://senbox.atlassian.net/browse/SNAP-3947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SNAP-3997]: https://senbox.atlassian.net/browse/SNAP-3997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SNAP-3997_product-library
